### ISSUE TITLE
Codebrag authenticity fails

### ISSUE THREAD

**Issue by shubhranshb06** [softwaremill/codebrag#104]
I am trying to sync my gitlab repo to codebag, but getting following error:

`09:36:15.366 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.repository.GitRepository - Cannot pull changes for repo /Users/shubhranshbhargava/Desktop/Codes/codebrag-2.3.4/repos/conveyor_management because of: ssh://git@robotgit.meditab.com:22: org.eclipse.jgit.transport.CredentialItem$YesNoType:The authenticity of host 'robotgit.meditab.com' can't be established.
RSA key fingerprint is c6:30:11:12:db:d9:0b:b9:a9:79:0d:51:f5:7c:43:aa.
Are you sure you want to continue connecting?
09:36:15.372 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream
org.eclipse.jgit.errors.UnsupportedCredentialItem: ssh://git@robotgit.meditab.com:22: org.eclipse.jgit.transport.CredentialItem$YesNoType:The authenticity of host 'robotgit.meditab.com' can't be established.
RSA key fingerprint is c6:30:11:12:db:d9:0b:b9:a9:79:0d:51:f5:7c:43:aa.
Are you sure you want to continue connecting?
	at org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider.get(UsernamePasswordCredentialsProvider.java:118) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.CredentialsProviderUserInfo.promptYesNo(CredentialsProviderUserInfo.java:124) ~[codebrag.jar:2.3.4]
	at com.jcraft.jsch.Session.checkHost(Session.java:785) ~[codebrag.jar:2.3.4]
	at com.jcraft.jsch.Session.connect(Session.java:342) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179) ~[codebrag.jar:2.3.4]
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128) ~[codebrag.jar:2.3.4]
	at com.softwaremill.codebrag.repository.GitRepository.pullChangesForRepo(GitRepository.scala:33) ~[codebrag.jar:2.3.4]
	at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:26) ~[codebrag.jar:2.3.4]
	at com.softwaremill.codebrag.repository.GitRepository.pullChanges(GitRepository.scala:15) ~[codebrag.jar:2.3.4]
	at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:22) ~[codebrag.jar:2.3.4]
	at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2.3.4]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.4]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.4]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.4]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.4]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.4]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.4]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.4]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.4]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.4]
09:36:38.414 [shutdownHook1] INFO  o.scalatra.servlet.ScalatraListener - Destroying life cycle class: ScalatraBootstrap
09:36:38.460 [shutdownHook1] INFO  o.e.j.server.handler.ContextHandler - stopped o.e.j.w.WebAppContext{/,file:/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jetty-0.0.0.0-8080-webapp-_-any-/webapp/},jar:file:/Users/shubhranshbhargava/Desktop/Codes/codebrag-2.3.4/codebrag.jar!/webapp
09:36:38.526 [shutdownHook1] INFO  com.softwaremill.codebrag.Codebrag$ - Codebrag stopped
`

My conf file is 
`repositories {

#    These are global settings, applied to all repositories if not overriden (see below)
#    Uncomment either username/password or passphrase depending on your git/svn repositories authentication method
#    username = "johndoe"
#    password = "secret_password"
#    passphrase = "secret_passphrase"

#    Repository-specific settings, applied to repository with given name
   conveyor_management {
       username = "shubhranshb"
       password = " "
   }

}`

my username is configured to global in git, name of repo is correct, what else can be wrong?

**Comment by gmkumar2005** [comment]
Did u try https ?

**Comment by shubhranshb06** [comment]
How to change the settings so that it take https?, I am not able to change it

**Comment by gmkumar2005** [comment]
you are using ssh://git@robotgit.meditab.com for your repository. Please try https://robotgit.meditab.com
