### ISSUE TITLE
Codebrang needs a restart every not and again

### ISSUE THREAD

**Issue by schrepfler** [softwaremill/codebrag#39]
I've noticed codebrag needs a restart as the frontend dissapears after some time.
Has anyone noticed this?
Couple of things I've noticed on the logs:
1) occasionally the git repo is not availible
```
Service - Cannot pull changes from upstream
org.eclipse.jgit.api.errors.TransportException: git@--------------------------.git: Session.connect: java.net.SocketException: C
onnection reset
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137) ~[codebrag.jar:2.3.1]
```
2) Noticed these exceptions in the logs when pressing "Mark commit as reviewed"
```
14:03:53.201 [qtp451189693-49] ERROR c.s.codebrag.rest.CommitsServlet - Something went wrong
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_26 ON PUBLIC.""reviewed_commits""(""user_id"", ""sha"", ""repo_name"") VALUES ( /* key:30 */ '54bcc8dce4b042c63284e4ff', 'f366990e1eddf12b1bdd1b6425258108f6d0e8f3', null, 'wh-debit-card-batch')"; SQL statement:
INSERT INTO "reviewed_commits" ("sha","user_id","repo_name","review_date") VALUES (?,?,?,?) [23505-175]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[codebrag.jar:2.3.1]

```

**Comment by jeffjensen** [comment]
Yes, we experience the same thing.  CB still sends the email notifications
but the UI is "down".  A restart and it works great again.

**Comment by mostr** [comment]
Weird, we haven't experienced it on our servers so far. @schrepfler, do you think these logs entries have something to do with the main issue or is it just "by the way" thing?

**Comment by schrepfler** [comment]
Not sure if it's related in any way. It seems something related with the presentation layer as the backend continues sending emails with the commits.
