### ISSUE TITLE
Help needed with GIT-SVN repos

### ISSUE THREAD

**Issue by arvindiway** [softwaremill/codebrag#42]
Hi,
I am trying to install codebrag, we have created the clone of our project from SVN using the git svn clone command. Our project SVN is SSH authenticated. Since i did not have access to clone, my sysadmin did it for me. Now after running the codebrag.bat codebrag comes up and shows a wait message that it is trying to get update from repository. However it hangs there. The log file shows a null pointer exception, when trying to get latest revision number. Below is the error trace.
15:29:57.285 [main] INFO  com.softwaremill.codebrag.Codebrag$ - Codebrag started on 0.0.0.0/0.0.0.0:8090
15:30:05.165 [Thread-19] INFO  c.s.c.repository.GitSvnRepository - fatal: bad revision 'HEAD'
15:30:05.171 [Thread-19] INFO  c.s.c.repository.GitSvnRepository - rev-list --first-parent --pretty=medium HEAD --: command returned error: 128
15:30:05.171 [Thread-19] INFO  c.s.c.repository.GitSvnRepository - 
15:30:05.223 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.s.commits.CommitImportService - Cannot import repository commits
java.lang.NullPointerException: null
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131) ~[codebrag.jar:2.3.1]
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:815) ~[codebrag.jar:2.3.1]
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:730) ~[codebrag.jar:2.3.1]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$class.setRangeStart(RepositoryDeltaLoader.scala:36) ~[codebrag.jar:2.3.1]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$class.com$softwaremill$codebrag$repository$RepositoryDeltaLoader$$getCommitsForBranch(RepositoryDeltaLoader.scala:18) ~[codebrag.jar:2.3.1]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$$anonfun$1.apply(RepositoryDeltaLoader.scala:28) ~[codebrag.jar:2.3.1]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$$anonfun$1.apply(RepositoryDeltaLoader.scala:27) ~[codebrag.jar:2.3.1]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[codebrag.jar:2.3.1]

I just followed the installation guide, i just gave a passphrase (as suggested). Do i have to configure the SSH key anywhere? Do i have to provide the passphrase of the user who did the clone? Please help with this.

**Comment by arvindiway** [comment]
Issue was with user not having proper permissions in SVN. Once that was resolved code brag was up and running.
