### ISSUE TITLE
Failed Preparing Email Template

### ISSUE THREAD

**Issue by sigeje** [softwaremill/codebrag#54]
I got this problem when sending my first invitation email. Then I opened the log up and found some information below.
```
09:20:05.628 [qtp1920387277-41] ERROR o.fusesource.scalate.TemplateEngine - Compilation failed:
error: error while loading CharSequence, class file 'C:\Program Files\Java\jre1.8.0_65\lib\rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 15 at byte 1470)
one error found

09:20:05.631 [qtp1920387277-41] ERROR c.s.codebrag.rest.InvitationServlet - Something went wrong
org.fusesource.scalate.CompilerException: Compilation failed:
error: error while loading CharSequence, class file 'C:\Program Files\Java\jre1.8.0_65\lib\rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 15 at byte 1470)
one error found

	at org.fusesource.scalate.support.ScalaCompiler.compile(ScalaCompiler.scala:105) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:757) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:699) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:419) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:413) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:471) ~[codebrag.jar:2.3.2]
	at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:573) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.templates.TemplateEngine.prepareEmailTemplate(TemplateEngine.scala:20) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.templates.TemplateEngine.getEmailTemplate(TemplateEngine.scala:16) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.invitations.InvitationService.invitationMessage(InvitationService.scala:48) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.invitations.InvitationService.sendInvitation(InvitationService.scala:26) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.usecases.SendInvitationEmailUseCase.execute(SendInvitationEmailUseCase.scala:13) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet$$anonfun$2.apply$mcV$sp(InvitationServlet.scala:19) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet$$anonfun$2.apply(InvitationServlet.scala:16) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet$$anonfun$2.apply(InvitationServlet.scala:16) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:250) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:245) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:245) ~[codebrag.jar:2.3.2]
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:175) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet.withRouteMultiParams(InvitationServlet.scala:7) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:244) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet.org$scalatra$json$JsonSupport$$super$invoke(InvitationServlet.scala:7) ~[codebrag.jar:2.3.2]
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:65) ~[codebrag.jar:2.3.2]
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:57) ~[codebrag.jar:2.3.2]
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:175) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet.withRouteMultiParams(InvitationServlet.scala:7) ~[codebrag.jar:2.3.2]
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:57) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.rest.InvitationServlet.invoke(InvitationServlet.scala:7) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$7.apply(ScalatraBase.scala:220) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$7.apply(ScalatraBase.scala:218) ~[codebrag.jar:2.3.2]
	at scala.Option.flatMap(Option.scala:170) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:218) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:217) ~[codebrag.jar:2.3.2]
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442) ~[codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:217) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:190) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [codebrag.jar:2.3.2]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.handle(ScalatraServlet.scala:49) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54) [codebrag.jar:2.3.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71) [codebrag.jar:2.3.2]
	at scala.Option.getOrElse(Option.scala:120) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166) [codebrag.jar:2.3.2]
	at scala.Option.getOrElse(Option.scala:120) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:190) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.executeRoutes(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.2]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.withResponse(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [codebrag.jar:2.3.2]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.withRequest(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.withRequestResponse(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.org$scalatra$servlet$ServletBase$$super$handle(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.handle(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33) [codebrag.jar:2.3.2]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.2]
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32) [codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.web.TimingFilter.doFilter(TimingFilter.scala:6) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.Server.handle(Server.java:365) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [codebrag.jar:2.3.2]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [codebrag.jar:2.3.2]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_65]
```

In addition, I installed the codebrag on local server with Windows 7 64 bit OS. The Java version is 7 update 21.

**Comment by sigeje** [comment]
Sorry, there was Java 8 installed on the server. Resolved by updating PATH environment variable to use JRE7 and move Java executable files in C:\Windows\System32.
