### ISSUE TITLE
ERROR c.s.c.repository.GitSvnRepository - Cannot pull changes for repo D:\codebrag-2.3.2\repos\trunk because of: No exit code: process destroyed.

### ISSUE THREAD

**Issue by Eleenrood** [softwaremill/codebrag#55]
From log:

11:54:30.599 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.repository.GitSvnRepository - Cannot pull changes for repo D:\codebrag-2.3.2\repos\trunk because of: No exit code: process destroyed.
11:54:30.602 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream
java.lang.RuntimeException: No exit code: process destroyed.
	at scala.sys.process.ProcessImpl$CompoundProcess.exitValue(ProcessImpl.scala:87) ~[codebrag.jar:2.3.2]
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$anonfun$runBuffered$1.apply(ProcessBuilderImpl.scala:147) ~[codebrag.jar:2.3.2]
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder$$anonfun$runBuffered$1.apply(ProcessBuilderImpl.scala:147) ~[codebrag.jar:2.3.2]
	at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:98) ~[codebrag.jar:2.3.2]
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:147) ~[codebrag.jar:2.3.2]
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$less(ProcessBuilderImpl.scala:115) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.repository.GitSvnRepository.runWithUserPassCredentials(GitSvnRepository.scala:29) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.repository.GitSvnRepository.runPullCommand(GitSvnRepository.scala:20) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.repository.GitSvnRepository.pullChangesForRepo(GitSvnRepository.scala:13) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:20) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.repository.GitSvnRepository.pullChanges(GitSvnRepository.scala:8) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:15) ~[codebrag.jar:2.3.2]
	at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2.3.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.2]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.2]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.2]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.2]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.2]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.2]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.2]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.2]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.2]

Do you need anything more?

**Comment by mostr** [comment]
Full log would be of help as well as config file. Where do you have your repository cloned? Is this in `repos/` and was initial clone successful?

**Comment by Eleenrood** [comment]
For deleted repository i've tried to initialized it by:
git svn clone PathToRepo FolderName

For branches and trunk repositories i've done it in two steps using 
git svn init PathToRepo FolderName
than git svn fetch

Both ways produced correct repositories, i can update them easily from command line. 

Then for both attempts i'm receiving the same error when it comes to pulling repo from codebrag. 

I'm on windows server 2008 r2 if thats relevant, with git 2.6.3.windows.1

Config file (XYZ replaced sensitive data, sorry ;) ) attached.

Full log from 1 day (there are error because of "DeletedRepository" - in attempt to fix it I've tried to change the way I've initialized repositories in ".repo" folder, deleted one repository folder and creating two additional ones)
[repoLog.txt](https://github.com/softwaremill/codebrag/files/47186/repoLog.txt)

[codebrag.conf.txt](https://github.com/softwaremill/codebrag/files/47187/codebrag.conf.txt)

**Comment by rusmichal** [comment]
Hello 

I have the same problem. I use bitbucket account to login.

I recevied this error:

```

org.eclipse.jgit.api.errors.TransportException: git@bitbucket.org:moodup/nemnet.git: Auth fail
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137) ~[codebrag.jar:2.3.2]
        at com.softwaremill.codebrag.repository.GitRepository.pullChangesForRepo(GitRepository.scala:30) ~[codebrag.jar:2.3.2]
        at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:20) ~[codebrag.jar:2.3.2]
        at com.softwaremill.codebrag.repository.GitRepository.pullChanges(GitRepository.scala:13) ~[codebrag.jar:2.3.2]
        at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:15) ~[codebrag.jar:2.3.2]
        at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2$
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.2]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.2]
Caused by: org.eclipse.jgit.errors.TransportException: git@bitbucket.org:moodup/nemnet.git: Auth fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:142) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1104) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128) ~[codebrag.jar:2.3.2]
        ... 14 common frames omitted
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:512) ~[codebrag.jar:2.3.2]
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116) ~[codebrag.jar:2.3.2]
```

**Comment by chiragkatudia** [comment]
Is there any solution of this problem ?

I facing the same while configuring Codebrag.  I could successfully clone the repo using git svn clone command but after starting codebrag - I am seeing same exception.

Any help would be really appreciated.

**Comment by Eleenrood** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Not that I'm aware of. We have moved to other (commercial) solutions - at that moment we are working with atlasian crucible. 
 
Dnia Wtorek, 28 Czerwca 2016 07:30 chiragkatudia <notifications@github.com> napisa³(a)

Is there any solution of this problem ?
I facing the same while configuring Codebrag. I could successfully clone the repo using git svn clone command but after starting codebrag - I am seeing same exception.
Any help would be really appreciated.
