### ISSUE TITLE
An error "oops, something went wrong on our side" popped out on the top right corner.

### ISSUE THREAD

**Issue by sherocktong** [softwaremill/codebrag#74]
There was a error dialog showing "oops, something went wrong on our side" on the top right corner. Then I couldn't login or do anything before I restart the server. I checked the codebrag.log and I found the error log below:
```
07:15:02.204 [codebrag-akka.actor.default-dispatcher-5] ERROR c.s.c.repository.GitRepository - Cannot pull changes for repo /root/codebrag-2.3.3/repos/dikup_wechat because of: https://120.26.236.133/plugins/git/dikupwechat/dikup_wechat.git: cannot open git-upload-pack
07:15:02.223 [codebrag-akka.actor.default-dispatcher-5] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream
org.eclipse.jgit.api.errors.TransportException: https://120.26.236.133/plugins/git/dikupwechat/dikup_wechat.git: cannot open git-upload-pack
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:134) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.GitRepository.pullChangesForRepo(GitRepository.scala:33) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:18) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.GitRepository.pullChanges(GitRepository.scala:15) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:22) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2.3.3]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.3]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.3]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.3]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.3]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.3]
Caused by: org.eclipse.jgit.errors.TransportException: https://120.26.236.133/plugins/git/dikupwechat/dikup_wechat.git: cannot open git-upload-pack
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:518) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128) ~[codebrag.jar:2.3.3]
        ... 14 common frames omitted
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355) ~[na:1.7.0_101]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.7.0_101]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.7.0_101]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302) ~[na:1.7.0_101]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468) ~[na:1.7.0_101]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.7.0_101]
        at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:174) ~[codebrag.jar:2.3.3]
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:469) ~[codebrag.jar:2.3.3]
        ... 19 common frames omitted
Caused by: java.security.ProviderException: java.security.KeyException
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:146) ~[sunec.jar:1.7.0_101]
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:704) ~[na:1.7.0_101]
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78) ~[na:1.7.0_101]
        at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:717) ~[na:1.7.0_101]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278) ~[na:1.7.0_101]
```

**Comment by lukaszlenart** [comment]
Looks like you are using Java with limited cryptology try this solution http://stackoverflow.com/questions/26066993/gitlab-cannot-open-git-upload-pack-error

**Comment by sherocktong** [comment]
I reinstalled JDK from Sun and the problem was solved.
