### ISSUE TITLE
 Invalid ref name: FETCH_HEAD

### ISSUE THREAD

**Issue by mikkushukla** [softwaremill/codebrag#77]
15:01:01.616 [codebrag-akka.actor.default-dispatcher-7] ERROR c.s.c.repository.GitRepository - Cannot pull changes for repo /mnt/vol
2/inmg01/manager/codebrag-2.3.3/repos/SmartHelmet because of: Invalid ref name: FETCH_HEAD
15:01:01.621 [codebrag-akka.actor.default-dispatcher-7] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstrea
m
org.eclipse.jgit.api.errors.JGitInternalException: Invalid ref name: FETCH_HEAD
        at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:160) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.GitRepository.pullChangesForRepo(GitRepository.scala:34) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:18) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.repository.GitRepository.pullChanges(GitRepository.scala:15) ~[codebrag.jar:2.3.3]
        at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:22) ~[codebrag.
jar:2.3.3]
        at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2.3.3]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.3]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.3]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.3]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.3]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.3]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.3]

**Comment by lukaszlenart** [comment]
And?

**Comment by mikkushukla** [comment]
And? it is not working for GIT repository? could you please fix this?

**Comment by mikkushukla** [comment]
Codebrag version 2.3.3 it is not supporting my GIT repository:(

**Comment by lukaszlenart** [comment]
It works for us so it must some configuration issue.

Can you enter `/mnt/vol2/inmg01/manager/codebrag-2.3.3/repos/SmartHelmet` and perform `git fetch`?

**Comment by mtippett** [comment]
FETCH_HEAD is the most recently fetched branch.  I worked around it in the same way as  @lukaszlenart's comment above.

A good starting reference is - https://www.atlassian.com/git/tutorials/refs-and-the-reflog/special-refs
