### ISSUE TITLE
Cannot repository commits from svn

### ISSUE THREAD

**Issue by zdihua** [softwaremill/codebrag#78]
09:42:13.810 [Thread-77] INFO  c.s.c.repository.GitSvnRepository - fatal: bad revision 'HEAD'
09:42:13.813 [Thread-77] INFO  c.s.c.repository.GitSvnRepository - rev-list --first-parent --pretty=medium HEAD --: command returned error: 128
09:42:13.813 [Thread-77] INFO  c.s.c.repository.GitSvnRepository - 
09:42:13.849 [codebrag-akka.actor.default-dispatcher-12] ERROR c.s.c.s.commits.CommitImportService - Cannot import repository commits
java.lang.NullPointerException: null
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131) ~[codebrag.jar:2.3.3]
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857) ~[codebrag.jar:2.3.3]
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$class.setRangeStart(RepositoryDeltaLoader.scala:36) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$class.com$softwaremill$codebrag$repository$RepositoryDeltaLoader$$getCommitsForBranch(RepositoryDeltaLoader.scala:18) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$$anonfun$1.apply(RepositoryDeltaLoader.scala:28) ~[codebrag.jar:2.3.3]
![Uploading Image 1.png…]()
	at com.softwaremill.codebrag.repository.RepositoryDeltaLoader$$anonfun$1.apply(RepositoryDeltaLoader.scala:27) ~[codebrag.jar:2.3.3]

**Comment by lukaszlenart** [comment]
Codebrag version?

**Comment by chiragkatudia** [comment]
I am facing the same problem.

As mentioned in install guide, I did cloning by using git svn clone  command, configured codebrag.conf file with username password for all the repo and started codebrag.

When I enter the URL, it says Downloading Data.... have coffee and come back and refresh the page.. I had three coffee after then :)  but same page.

When I checked the log, it shows same error as mentioned above by @zdihua 

Codebra version : 2.3.4

Please help.

**Comment by nickrfer** [comment]
I had the same problem but got it fixed by explicitly specifying the latest revision number and the username parameter:
git svn clone --username myusername -r140123 https://mysvnurl.com/repo

Hope this helps!
