### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by sherocktong** [softwaremill/codebrag#79]
Here is the log from codebrag.log below:
14:49:46.672 [qtp681788706-35] ERROR c.s.codebrag.rest.SessionServlet - Something went wrong
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39) ~[codebrag.jar:2.3.3]
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37) ~[codebrag.jar:2.3.3]
	at scala.collection.IterableLike$class.head(IterableLike.scala:91) ~[codebrag.jar:2.3.3]
	at scala.collection.AbstractIterable.head(Iterable.scala:54) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.finders.browsingcontext.UserBrowsingContextFinder$$anonfun$2.apply(UserBrowsingContextFinder.scala:45) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.finders.browsingcontext.UserBrowsingContextFinder$$anonfun$2.apply(UserBrowsingContextFinder.scala:39) ~[codebrag.jar:2.3.3]
	at scala.Option.map(Option.scala:145) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.finders.browsingcontext.UserBrowsingContextFinder.findUserDefaultContext(UserBrowsingContextFinder.scala:39) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.finders.user.UserFinder.findLoggedInUser(UserFinder.scala:15) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.usecases.user.LoginUserUseCase$$anonfun$execute$1$$anonfun$apply$1.apply(LoginUserUseCase.scala:17) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.usecases.user.LoginUserUseCase$$anonfun$execute$1$$anonfun$apply$1.apply(LoginUserUseCase.scala:17) ~[codebrag.jar:2.3.3]
	at scala.Option.map(Option.scala:145) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.usecases.user.LoginUserUseCase$$anonfun$execute$1.apply(LoginUserUseCase.scala:17) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.usecases.user.LoginUserUseCase$$anonfun$execute$1.apply(LoginUserUseCase.scala:15) ~[codebrag.jar:2.3.3]
	at com.softwaremill.scalaval.Validation$Result.whenOk(Validation.scala:19) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.usecases.user.LoginUserUseCase.execute(LoginUserUseCase.scala:15) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.rest.SessionServlet$$anonfun$2.apply(SessionServlet.scala:12) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:250) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:245) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:245) ~[codebrag.jar:2.3.3]
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:175) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.rest.SessionServlet.withRouteMultiParams(SessionServlet.scala:8) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:244) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.rest.SessionServlet.org$scalatra$json$JsonSupport$$super$invoke(SessionServlet.scala:8) ~[codebrag.jar:2.3.3]
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:65) ~[codebrag.jar:2.3.3]
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:57) ~[codebrag.jar:2.3.3]
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:175) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.rest.SessionServlet.withRouteMultiParams(SessionServlet.scala:8) ~[codebrag.jar:2.3.3]
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:57) ~[codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.rest.SessionServlet.invoke(SessionServlet.scala:8) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$7.apply(ScalatraBase.scala:220) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$7.apply(ScalatraBase.scala:218) ~[codebrag.jar:2.3.3]
	at scala.Option.flatMap(Option.scala:170) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:218) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:217) ~[codebrag.jar:2.3.3]
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442) ~[codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:217) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:190) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [codebrag.jar:2.3.3]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.handle(ScalatraServlet.scala:49) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54) [codebrag.jar:2.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71) [codebrag.jar:2.3.3]
	at scala.Option.getOrElse(Option.scala:120) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166) [codebrag.jar:2.3.3]
	at scala.Option.getOrElse(Option.scala:120) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:190) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.executeRoutes(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [codebrag.jar:2.3.3]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.withResponse(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [codebrag.jar:2.3.3]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.withRequest(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.withRequestResponse(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.org$scalatra$servlet$ServletBase$$super$handle(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.handle(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33) [codebrag.jar:2.3.3]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [codebrag.jar:2.3.3]
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32) [codebrag.jar:2.3.3]
	at com.softwaremill.codebrag.web.TimingFilter.doFilter(TimingFilter.scala:6) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.Server.handle(Server.java:365) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [codebrag.jar:2.3.3]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [codebrag.jar:2.3.3]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

**Comment by lukaszlenart** [comment]
Please restart Codebrag

**Comment by sherocktong** [comment]
Is there any patches to fix that? I got this error for several times.

**Comment by lukaszlenart** [comment]
Looks like you have users without assigned branches or something

**Comment by alexb5** [comment]
I have this bug on enter with administrator. What i have to do now?

**Comment by thangaswamyarun** [comment]
I am also facing the same problem frequently. Any help?
