### ISSUE TITLE
Authentication is required but no CredentialsProvider has been registered

### ISSUE THREAD

**Issue by smruti-sahoo** [softwaremill/codebrag#80]
Hey, I'm getting following error post startup

```
org.eclipse.jgit.api.errors.TransportException: https://xxx/xx-test.git: Authentication is required but no CredentialsProvider has been registered
```

I provided the credentials in .conf file inside repo_name still same issue
plz let me know if you need any more logs.. 

Many thanks in advance

**Comment by lukaszlenart** [comment]
`.conf` file must be in app root, not in `repo_name`

**Comment by smruti-sahoo** [comment]
Yes - It's in app root 
codebrag.conf in /opt/codebrag/

**Comment by smruti-sahoo** [comment]
18:47:19.737 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.repository.GitRepository - Cannot pull changes for repo /opt/codebrag/repos/xxxx-yyy because of: https://<github_ip>/xxxx/xxxx-yyy.git: Authentication is required but no CredentialsProvider has been registered
18:47:19.737 [codebrag-akka.actor.default-dispatcher-3] ERROR c.s.c.s.commits.CommitImportService - Cannot pull changes from upstream
org.eclipse.jgit.api.errors.TransportException: https://<github_ip>/xxxx/xxxx-yyy.git: A**_uthentication is required but no CredentialsProvider has been registered_**
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:134) ~[codebrag.jar:2.3.4]
        at com.softwaremill.codebrag.repository.GitRepository.pullChangesForRepo(GitRepository.scala:33) ~[codebrag.jar:2.3.4]
        at com.softwaremill.codebrag.repository.Repository$class.pullChanges(Repository.scala:26) ~[codebrag.jar:2.3.4]
        at com.softwaremill.codebrag.repository.GitRepository.pullChanges(GitRepository.scala:15) ~[codebrag.jar:2.3.4]
        at com.softwaremill.codebrag.service.commits.CommitImportService.importRepoCommits(CommitImportService.scala:22) ~[codebrag.jar:2.3.4]
        at com.softwaremill.codebrag.service.updater.RepoUpdateActor$$anonfun$receive$1.applyOrElse(RepoUpdateActor.scala:14) [codebrag.jar:2.3.4]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [codebrag.jar:2.3.4]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [codebrag.jar:2.3.4]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [codebrag.jar:2.3.4]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [codebrag.jar:2.3.4]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [codebrag.jar:2.3.4]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [codebrag.jar:2.3.4]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [codebrag.jar:2.3.4]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [codebrag.jar:2.3.4]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [codebrag.jar:2.3.4]
Caused by: org.eclipse.jgit.errors.TransportException: https://<github_ip>/xxxx/xxxx-yyy.git: Authentication is required but no CredentialsProvider has been registered
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:492) ~[codebrag.jar:2.3.4]
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296) ~[codebrag.jar:2.3.4]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[codebrag.jar:2.3.4]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[codebrag.jar:2.3.4]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179) ~[codebrag.jar:2.3.4]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128) ~[codebrag.jar:2.3.4]
        ... 14 common frames omitted

**Comment by lukaszlenart** [comment]
Can you provide your `.conf` file?

**Comment by smruti-sahoo** [comment]
repositories {

   repo_name {
        username = "user"    
        password = "password"
    }
}

codebrag {
    data-dir = "./data"
    repos-root = "./repos"
    send-anon-usage-data = false
    web-server-port = 8080
    application-url = "http://localhost:8080"

   required-reviewers-count = 1

   pull-sleep-period {
        enabled = false
        from = 22
        to = 5
    }
}

I've removed email and hook section as I've not setup the mail server yet

**Comment by lukaszlenart** [comment]
Does `repo_name` matches name of you repo? ie. my repo name is `codebrag` so it must be
```
repositories {

   codebrag {
        username = "user"    
        password = "password"
    }
}
```

**Comment by smruti-sahoo** [comment]
Grrr.. yeah that's working now with my repo .. Many thanks.. 
I'm using this tool for first time today and I really like it :+1: 
Tomorrow I'll play around other features and let see how it's going 

Thanks again for very quick response

**Comment by lukaszlenart** [comment]
👍

**Comment by vinayreach** [comment]
hello
i am facing the same issue, can I know like where is my .conf file located.

**Comment by santoshalld3112** [comment]
I am getting this error all the time ... what am I doing wrong ?

[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform (default-cli) on project spring-boot-rest-example: The local working copy which has been built is out of sync with the remote repository. [Local revision: af16a176887f6a679a91a6ed2ad28a6f555e8ef3] [Latest remote revision: ] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform (default-cli) on project spring-boot-rest-example: The local working copy which has been built is out of sync with the remote repository. [Local revision: af16a176887f6a679a91a6ed2ad28a6f555e8ef3] [Latest remote revision: ]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoFailureException: The local working copy which has been built is out of sync with the remote repository. [Local revision: af16a176887f6a679a91a6ed2ad28a6f555e8ef3] [Latest remote revision: ]
	at com.itemis.maven.plugins.unleash.steps.checks.CheckScmChanges.execute(CheckScmChanges.java:50)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:131)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:114)
	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:207)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[JENKINS] Archiving C:\Users\santosh_kumar51\.jenkins\workspace\testRelease_jfrog\pom.xml to com.khoubyari/spring-boot-rest-example/100/spring-boot-rest-example-100.pom
channel stopped
Finished: FAILURE
